### ISSUE TITLE
400 No required SSL certificate was sent

### ISSUE THREAD

**Issue by partounian** [TypistTech/trellis-cloudflare-origin-ca#34]
## Submit a feature request or bug report

- [x] I've read the [code of conduct](https://github.com/TypistTech/trellis-cloudflare-origin-ca/blob/master/CODE_OF_CONDUCT.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/TypistTech/trellis-cloudflare-origin-ca/issues)
- [x] I've read the project [readme](https://github.com/TypistTech/trellis-cloudflare-origin-ca) and followed them (if applicable)
- [x] I've read the [Trellis docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a Trellis support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums or [Trellis' issue tracker](https://github.com/roots/trellis/issues)
- [x] This is not a Cloudflare support request that should be reported to [Cloudflare support team](https://support.cloudflare.com/)

Replace any `X` with your information.

---

**What is the current behavior?**

400 Bad Request
No required SSL certificate was sent after running `ansible-playbook server.yml -e env=staging -t cloudflare-origin-ca`

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X Somehow nothing in nginx logs.

**Please describe your local environment:**

Ansible version: 2.5

OS: macOS 10.13.3

Vagrant version: n/a

Trellis commit:  9dfddfd  

**Where did the bug happen? Development or remote servers?**

X Remote

**Why don't you create a pull request to fix it?**

X Not sure what causes the error

**Other relevant information:**

X Cloudflare has generated the Origin cert, and it seems client cert field has been updated in nginx config.

**Comment by partounian** [comment]
It works now, probably related to #33 .

**Comment by partounian** [comment]
I don't believe so, as I have fixed that.
Yes all of the files are there.
```
# Ansible managed

# Cloudflare Origin CA

ssl_certificate /etc/nginx/ssl/cloudflare-origin-ca/imi.org.pem;
ssl_certificate_key /etc/nginx/ssl/cloudflare-origin-ca/imi.org.key;
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by TangRufus** [comment]
> client sent no required SSL certificate while reading client request headers

Looks like 108.162.215.129(cloudflare) is not sending a client cert. 

Do you have `ssl_verify_client on;` in Nginx config files or using https://github.com/roots/trellis/pull/869?

If yes, contact Cloudflare support.

**Comment by partounian** [comment]
`ssl_verify_client on;` is on, and I am up to date with Trellis. When I contact them what should I say specifically?

**Comment by partounian** [comment]
Do you have to enabled Authenticated Origin Pulls for that?

**Comment by TangRufus** [comment]
Background: I am using https://github.com/roots/trellis/pull/869

---

When I disable "Authenticated Origin Pulls" from Cloudflare dashboard, i got:
```
400 Bad Request
No required SSL certificate was sent
```

---

Everything works fine when I re-enable it.

![typist_tech___cloudflare_-_web_performance___security](https://user-images.githubusercontent.com/2259834/38751889-081d24ba-3f8c-11e8-9801-bf5a82b54ae7.jpg)

---

This issue isn't about this role (the ssl cert in `/etc/nginx/ssl/cloudflare-origin-ca`). 
The issue is `ssl_verify_client on;` but cloudflare doesn't send you a client cert.

If you still getting 400 errors after enabling "Authenticated Origin Pulls", send your nginx debug output to cloudflare support.

**Comment by partounian** [comment]
Maybe this plugin should not require that if it is not required just for Full strict SSL?

The problem with enabling that is that it will break everything on the domain name if it doesn't have the cloudflare client cert.

**Comment by TangRufus** [comment]
This role never add `ssl_verify_client on;`!

---

More about this 400 error:

This is actually good behaviour. It ensure all requests come through Cloudflare. Thus, all requests are protected by Cloudflare's firewall, page rules, ssl settings, etc

**Comment by TangRufus** [comment]
![](https://cloudflare.ghost.io/content/images/2015/02/illustration-tls-ssl-client-auth.png)

Step 3 is initiated by your server, I **believe** you can disable `ssl_verify_client` even with "Authenticated Origin Pulls" is on.

**Comment by partounian** [comment]
Thank you my mistake was copying your project-template for trellis instead of just paying attention to the readme for this.
