### ISSUE TITLE
Does this autorenew certificates?

### ISSUE THREAD

**Issue by aaronjpitts** [TypistTech/trellis-cloudflare-origin-ca#40]
Hi, simple question. You have set the certificate days default value to 7. What happens when the certificate generated by this expires? Does it auto renew or do you have to reprovision the take again to generate a new one?

Many thanks

**Comment by TangRufus** [comment]
> Does this autorenew certificates?

No.

> What happens when the certificate generated by this expires? 

Nothing on the server. 
And, you will get invalid SSL certificate errors when visiting via web web browsers.

> do you have to reprovision the take again to generate a new one?

To renew a cert:
1. Remove old certificates from `/etc/nginx/ssl/cloudflare-origin-ca`
2. Reprovision

More info here - https://discourse.roots.io/t/site-on-trellis-provisioned-do-droplet-subdom-site-on-2nd-droplet-cloudflare-oc/14516/9
