### ISSUE TITLE
Failing on Add Cloudflare key - pubkey 404

### ISSUE THREAD

**Issue by aaronjpitts** [TypistTech/trellis-cloudflare-origin-ca#61]
Hello,

I've used your package several times. Now when trying to reprovision a new server it is failing with the below. Any ideas? All my setup is correct as I have used your package before.

Many thanks,
Aaron

```
TASK [TypistTech.trellis-cloudflare-origin-ca : Add Cloudflare key] ************
fatal: [***********]: FAILED! => {"changed": false, "msg": "Failed to download key at https://pkg.cloudflare.com/pubkey.gpg: HTTP Error 404: Not Found"}
```

**Comment by tangrufus** [comment]
Cloudflare removed `cfca` from their ppa.
This role is unusable until we find an alternative.
See: https://github.com/TypistTech/trellis-cloudflare-origin-ca/pull/59
